apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pact-broker
  name: pact-broker
  namespace: pact
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 32033
  selector:
    io.kompose.service: pact-broker
  type: LoadBalancer
